name: flutter_application_6
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/vios.jpg
    - assets/images/city.jpg
    - assets/images/myvi.jpg
    - assets/images/x70.jpg
    - assets/images/welcome_car.png
    - assets/images/real_bg.jpg
